# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(802, 445)
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        MainWindow.setWindowOpacity(1.0)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(101, 16777215))
        self.frame.setStyleSheet("background-color: rgb(85, 87, 83);")
        self.frame.setObjectName("frame")
        self._2 = QtWidgets.QVBoxLayout(self.frame)
        self._2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self._2.setContentsMargins(6, 11, 6, 11)
        self._2.setSpacing(6)
        self._2.setObjectName("_2")
        self.imgPOD = QtWidgets.QGraphicsView(self.frame)
        self.imgPOD.setMaximumSize(QtCore.QSize(16777215, 24))
        self.imgPOD.setAutoFillBackground(False)
        self.imgPOD.setStyleSheet("border-image: url(:/new/prefix1/LogoWhite.png);")
        self.imgPOD.setObjectName("imgPOD")
        self._2.addWidget(self.imgPOD)
        self.lblAvailable = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAvailable.sizePolicy().hasHeightForWidth())
        self.lblAvailable.setSizePolicy(sizePolicy)
        self.lblAvailable.setStyleSheet("color: rgb(211, 215, 207);")
        self.lblAvailable.setObjectName("lblAvailable")
        self._2.addWidget(self.lblAvailable)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self._2.addWidget(self.line)
        self.btnExperimentInfo = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExperimentInfo.sizePolicy().hasHeightForWidth())
        self.btnExperimentInfo.setSizePolicy(sizePolicy)
        self.btnExperimentInfo.setMaximumSize(QtCore.QSize(16777215, 64))
        self.btnExperimentInfo.setStyleSheet("color: rgb(211, 215, 207);")
        self.btnExperimentInfo.setObjectName("btnExperimentInfo")
        self._2.addWidget(self.btnExperimentInfo)
        self.btnNew = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNew.sizePolicy().hasHeightForWidth())
        self.btnNew.setSizePolicy(sizePolicy)
        self.btnNew.setMaximumSize(QtCore.QSize(16777215, 64))
        self.btnNew.setStyleSheet("color: rgb(211, 215, 207);")
        self.btnNew.setObjectName("btnNew")
        self._2.addWidget(self.btnNew)
        self.btnHelp = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnHelp.sizePolicy().hasHeightForWidth())
        self.btnHelp.setSizePolicy(sizePolicy)
        self.btnHelp.setMaximumSize(QtCore.QSize(16777215, 64))
        self.btnHelp.setStyleSheet("color: rgb(211, 215, 207);")
        self.btnHelp.setObjectName("btnHelp")
        self._2.addWidget(self.btnHelp)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self._2.addItem(spacerItem)
        self.horizontalLayout_2.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.centralWidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_3)
        self.stackedWidget.setMaximumSize(QtCore.QSize(16777214, 16777215))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblNoExp = QtWidgets.QLabel(self.page)
        self.lblNoExp.setMaximumSize(QtCore.QSize(16777215, 200))
        self.lblNoExp.setObjectName("lblNoExp")
        self.verticalLayout_2.addWidget(self.lblNoExp)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.page_2.setObjectName("page_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.page_2)
        self.frame_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout.setContentsMargins(0, 0, 0, 11)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.lblStartNew = QtWidgets.QLabel(self.frame_2)
        self.lblStartNew.setObjectName("lblStartNew")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblStartNew)
        self.lblName = QtWidgets.QLabel(self.frame_2)
        self.lblName.setMaximumSize(QtCore.QSize(16777215, 100))
        self.lblName.setObjectName("lblName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblName)
        self.txtName = QtWidgets.QPlainTextEdit(self.frame_2)
        self.txtName.setMaximumSize(QtCore.QSize(16777215, 30))
        self.txtName.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtName.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.txtName.setTabChangesFocus(True)
        self.txtName.setPlainText("")
        self.txtName.setBackgroundVisible(False)
        self.txtName.setCenterOnScroll(False)
        self.txtName.setPlaceholderText("")
        self.txtName.setObjectName("txtName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtName)
        self.lblDays = QtWidgets.QLabel(self.frame_2)
        self.lblDays.setObjectName("lblDays")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblDays)
        self.spnDays = QtWidgets.QSpinBox(self.frame_2)
        self.spnDays.setMinimum(1)
        self.spnDays.setObjectName("spnDays")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spnDays)
        self.lblPhotos = QtWidgets.QLabel(self.frame_2)
        self.lblPhotos.setObjectName("lblPhotos")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblPhotos)
        self.spnPhotos = QtWidgets.QSpinBox(self.frame_2)
        self.spnPhotos.setMinimum(1)
        self.spnPhotos.setObjectName("spnPhotos")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spnPhotos)
        self.lblWater = QtWidgets.QLabel(self.frame_2)
        self.lblWater.setObjectName("lblWater")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lblWater)
        self.spnWater = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.spnWater.setObjectName("spnWater")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spnWater)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.line_6 = QtWidgets.QFrame(self.page_2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_4.addWidget(self.line_6)
        self.btnNext = QtWidgets.QPushButton(self.page_2)
        self.btnNext.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btnNext.setAutoDefault(False)
        self.btnNext.setDefault(False)
        self.btnNext.setFlat(False)
        self.btnNext.setObjectName("btnNext")
        self.verticalLayout_4.addWidget(self.btnNext)
        self.stackedWidget.addWidget(self.page_2)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblGroups = QtWidgets.QLabel(self.page_4)
        self.lblGroups.setObjectName("lblGroups")
        self.horizontalLayout.addWidget(self.lblGroups)
        self.btnAddGroup = QtWidgets.QPushButton(self.page_4)
        self.btnAddGroup.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btnAddGroup.setAutoRepeatInterval(100)
        self.btnAddGroup.setObjectName("btnAddGroup")
        self.horizontalLayout.addWidget(self.btnAddGroup)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.line_8 = QtWidgets.QFrame(self.page_4)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_5.addWidget(self.line_8)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblUnassigned = QtWidgets.QLabel(self.page_4)
        self.lblUnassigned.setObjectName("lblUnassigned")
        self.verticalLayout_3.addWidget(self.lblUnassigned, 0, QtCore.Qt.AlignLeft)
        self.lstUnassigned = QtWidgets.QListWidget(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lstUnassigned.sizePolicy().hasHeightForWidth())
        self.lstUnassigned.setSizePolicy(sizePolicy)
        self.lstUnassigned.setMinimumSize(QtCore.QSize(200, 0))
        self.lstUnassigned.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lstUnassigned.setAcceptDrops(True)
        self.lstUnassigned.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lstUnassigned.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.lstUnassigned.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.lstUnassigned.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.lstUnassigned.setViewMode(QtWidgets.QListView.ListMode)
        self.lstUnassigned.setObjectName("lstUnassigned")
        self.verticalLayout_3.addWidget(self.lstUnassigned, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.line_5 = QtWidgets.QFrame(self.page_4)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_3.addWidget(self.line_5)
        self.scrollArea = QtWidgets.QScrollArea(self.page_4)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrGroupLayout = QtWidgets.QWidget()
        self.scrGroupLayout.setGeometry(QtCore.QRect(0, 0, 472, 343))
        self.scrGroupLayout.setObjectName("scrGroupLayout")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.scrGroupLayout)
        self.verticalLayout_14.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.lyt_scroll = QtWidgets.QHBoxLayout()
        self.lyt_scroll.setContentsMargins(1, 1, 1, 1)
        self.lyt_scroll.setSpacing(6)
        self.lyt_scroll.setObjectName("lyt_scroll")
        self.verticalLayout_14.addLayout(self.lyt_scroll)
        self.scrollArea.setWidget(self.scrGroupLayout)
        self.horizontalLayout_3.addWidget(self.scrollArea)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.line_7 = QtWidgets.QFrame(self.page_4)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_5.addWidget(self.line_7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnGroupBack = QtWidgets.QPushButton(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGroupBack.sizePolicy().hasHeightForWidth())
        self.btnGroupBack.setSizePolicy(sizePolicy)
        self.btnGroupBack.setMinimumSize(QtCore.QSize(125, 0))
        self.btnGroupBack.setMaximumSize(QtCore.QSize(125, 16777215))
        self.btnGroupBack.setObjectName("btnGroupBack")
        self.horizontalLayout_4.addWidget(self.btnGroupBack)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.btnGroupStart = QtWidgets.QPushButton(self.page_4)
        self.btnGroupStart.setMaximumSize(QtCore.QSize(125, 16777215))
        self.btnGroupStart.setObjectName("btnGroupStart")
        self.horizontalLayout_4.addWidget(self.btnGroupStart)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.stackedWidget.addWidget(self.page_4)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label = QtWidgets.QLabel(self.page_3)
        self.label.setGeometry(QtCore.QRect(0, 0, 671, 71))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.page_3)
        self.label_2.setGeometry(QtCore.QRect(0, 90, 541, 17))
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.page_3)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_13.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_13.setSpacing(6)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_12.setSpacing(6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.lbl_exp_name = QtWidgets.QLabel(self.page_5)
        self.lbl_exp_name.setObjectName("lbl_exp_name")
        self.verticalLayout_12.addWidget(self.lbl_exp_name)
        self.lbl_exp_day = QtWidgets.QLabel(self.page_5)
        self.lbl_exp_day.setObjectName("lbl_exp_day")
        self.verticalLayout_12.addWidget(self.lbl_exp_day)
        self.line_3 = QtWidgets.QFrame(self.page_5)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_12.addWidget(self.line_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_15.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_15.setSpacing(6)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.lbl_exp_pods = QtWidgets.QLabel(self.page_5)
        self.lbl_exp_pods.setObjectName("lbl_exp_pods")
        self.verticalLayout_15.addWidget(self.lbl_exp_pods)
        self.lst_exp_pods = QtWidgets.QListWidget(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lst_exp_pods.sizePolicy().hasHeightForWidth())
        self.lst_exp_pods.setSizePolicy(sizePolicy)
        self.lst_exp_pods.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lst_exp_pods.setObjectName("lst_exp_pods")
        self.verticalLayout_15.addWidget(self.lst_exp_pods)
        self.horizontalLayout_6.addLayout(self.verticalLayout_15)
        self.line_4 = QtWidgets.QFrame(self.page_5)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_6.addWidget(self.line_4)
        self.frame_5 = QtWidgets.QFrame(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 25))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout.setContentsMargins(1, 1, 1, 1)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_exp_light = QtWidgets.QLabel(self.frame_5)
        self.lbl_exp_light.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lbl_exp_light.setObjectName("lbl_exp_light")
        self.gridLayout.addWidget(self.lbl_exp_light, 2, 0, 1, 1)
        self.lbl_exp_network = QtWidgets.QLabel(self.frame_5)
        self.lbl_exp_network.setObjectName("lbl_exp_network")
        self.gridLayout.addWidget(self.lbl_exp_network, 4, 0, 1, 1)
        self.lbl_exp_on = QtWidgets.QLabel(self.frame_5)
        self.lbl_exp_on.setObjectName("lbl_exp_on")
        self.gridLayout.addWidget(self.lbl_exp_on, 5, 0, 1, 1)
        self.lbl_exp_off = QtWidgets.QLabel(self.frame_5)
        self.lbl_exp_off.setObjectName("lbl_exp_off")
        self.gridLayout.addWidget(self.lbl_exp_off, 6, 0, 1, 1)
        self.lbl_exp_temp = QtWidgets.QLabel(self.frame_5)
        self.lbl_exp_temp.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lbl_exp_temp.setObjectName("lbl_exp_temp")
        self.gridLayout.addWidget(self.lbl_exp_temp, 3, 0, 1, 1)
        self.frm_temp = QtWidgets.QFrame(self.frame_5)
        self.frm_temp.setMinimumSize(QtCore.QSize(0, 25))
        self.frm_temp.setMaximumSize(QtCore.QSize(40, 16777215))
        self.frm_temp.setStyleSheet("background-color: rgb(128, 255, 107);")
        self.frm_temp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_temp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_temp.setObjectName("frm_temp")
        self.gridLayout.addWidget(self.frm_temp, 3, 1, 1, 1)
        self.lbl_on_sec = QtWidgets.QLabel(self.frame_5)
        self.lbl_on_sec.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_on_sec.setObjectName("lbl_on_sec")
        self.gridLayout.addWidget(self.lbl_on_sec, 5, 1, 1, 1)
        self.frm_network = QtWidgets.QFrame(self.frame_5)
        self.frm_network.setMinimumSize(QtCore.QSize(0, 25))
        self.frm_network.setMaximumSize(QtCore.QSize(40, 16777215))
        self.frm_network.setStyleSheet("background-color: rgb(128, 255, 107);")
        self.frm_network.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_network.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_network.setObjectName("frm_network")
        self.gridLayout.addWidget(self.frm_network, 4, 1, 1, 1)
        self.lbl_brightness_percent = QtWidgets.QLabel(self.frame_5)
        self.lbl_brightness_percent.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_brightness_percent.setObjectName("lbl_brightness_percent")
        self.gridLayout.addWidget(self.lbl_brightness_percent, 7, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 9, 0, 1, 1)
        self.lbl_exp_podid = QtWidgets.QLabel(self.frame_5)
        self.lbl_exp_podid.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lbl_exp_podid.setObjectName("lbl_exp_podid")
        self.gridLayout.addWidget(self.lbl_exp_podid, 0, 0, 1, 1)
        self.frm_light = QtWidgets.QFrame(self.frame_5)
        self.frm_light.setMinimumSize(QtCore.QSize(0, 25))
        self.frm_light.setMaximumSize(QtCore.QSize(40, 16777215))
        self.frm_light.setStyleSheet("background-color: rgb(128, 255, 107);")
        self.frm_light.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_light.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_light.setObjectName("frm_light")
        self.gridLayout.addWidget(self.frm_light, 2, 1, 1, 1)
        self.lbl_overall_status = QtWidgets.QLabel(self.frame_5)
        self.lbl_overall_status.setObjectName("lbl_overall_status")
        self.gridLayout.addWidget(self.lbl_overall_status, 1, 0, 1, 1)
        self.frm_overall = QtWidgets.QFrame(self.frame_5)
        self.frm_overall.setMinimumSize(QtCore.QSize(40, 25))
        self.frm_overall.setMaximumSize(QtCore.QSize(40, 16777215))
        self.frm_overall.setStyleSheet("background-color: rgb(128, 255, 107);")
        self.frm_overall.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_overall.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_overall.setObjectName("frm_overall")
        self.gridLayout.addWidget(self.frm_overall, 1, 1, 1, 1)
        self.lbl_exp_brightness = QtWidgets.QLabel(self.frame_5)
        self.lbl_exp_brightness.setObjectName("lbl_exp_brightness")
        self.gridLayout.addWidget(self.lbl_exp_brightness, 7, 0, 1, 1)
        self.lbl_off_sec = QtWidgets.QLabel(self.frame_5)
        self.lbl_off_sec.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_off_sec.setObjectName("lbl_off_sec")
        self.gridLayout.addWidget(self.lbl_off_sec, 6, 1, 1, 1)
        self.horizontalLayout_6.addWidget(self.frame_5)
        self.verticalLayout_12.addLayout(self.horizontalLayout_6)
        self.line_2 = QtWidgets.QFrame(self.page_5)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_12.addWidget(self.line_2)
        self.btn_exp_cancel = QtWidgets.QPushButton(self.page_5)
        self.btn_exp_cancel.setMaximumSize(QtCore.QSize(125, 16777215))
        self.btn_exp_cancel.setObjectName("btn_exp_cancel")
        self.verticalLayout_12.addWidget(self.btn_exp_cancel, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.stackedWidget.addWidget(self.page_5)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "POD"))
        self.lblAvailable.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">xx Available</p></body></html>"))
        self.btnExperimentInfo.setText(_translate("MainWindow", "Experiment\n"
"Status"))
        self.btnNew.setText(_translate("MainWindow", "New"))
        self.btnHelp.setText(_translate("MainWindow", "Help"))
        self.lblNoExp.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">No Experiment Currently Running</span></p><p align=\"center\"><span style=\" font-size:14pt;\">Press &quot;New&quot; to Start a New Experiment</span></p></body></html>"))
        self.lblStartNew.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Start New Experiment</span></p></body></html>"))
        self.lblName.setText(_translate("MainWindow", "Experiment Name:"))
        self.lblDays.setText(_translate("MainWindow", "Experiment Duration (Days):"))
        self.lblPhotos.setText(_translate("MainWindow", "Photos per Day: "))
        self.lblWater.setText(_translate("MainWindow", "Water Pump On (Seconds)"))
        self.btnNext.setText(_translate("MainWindow", "Next"))
        self.lblGroups.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Experiment Groups</span></p></body></html>"))
        self.btnAddGroup.setText(_translate("MainWindow", "Add Group"))
        self.lblUnassigned.setText(_translate("MainWindow", "Unassigned PODs"))
        self.btnGroupBack.setText(_translate("MainWindow", "Back"))
        self.btnGroupStart.setText(_translate("MainWindow", "Start Experiment"))
        self.label.setText(_translate("MainWindow", "Experiment Status shows the status of the current experiment. \n"
"If no experiment is running, it prompts you to start a new experiment. \n"
"You can cancel an experiment on the Experiment Status page."))
        self.label_2.setText(_translate("MainWindow", "You can start a new experiment by clicking New and filling out information. "))
        self.lbl_exp_name.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Experiment Name:</span></p></body></html>"))
        self.lbl_exp_day.setText(_translate("MainWindow", "Day x/xx"))
        self.lbl_exp_pods.setText(_translate("MainWindow", "PODs in Experiment"))
        self.lbl_exp_light.setText(_translate("MainWindow", "Light Sensor"))
        self.lbl_exp_network.setText(_translate("MainWindow", "Network Connection"))
        self.lbl_exp_on.setText(_translate("MainWindow", "Light On Time"))
        self.lbl_exp_off.setText(_translate("MainWindow", "Light Off Time"))
        self.lbl_exp_temp.setText(_translate("MainWindow", "Temperature Sensor"))
        self.lbl_on_sec.setText(_translate("MainWindow", "XXXs"))
        self.lbl_brightness_percent.setText(_translate("MainWindow", "XX%"))
        self.lbl_exp_podid.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">POD XXX</span></p></body></html>"))
        self.lbl_overall_status.setText(_translate("MainWindow", "Overall Status"))
        self.lbl_exp_brightness.setText(_translate("MainWindow", "Light Brightness"))
        self.lbl_off_sec.setText(_translate("MainWindow", "XXXs"))
        self.btn_exp_cancel.setText(_translate("MainWindow", "Cancel\n"
"Experiment"))

